AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 Bucket privado com versionamento opcional'

Parameters:
  BucketName:
    Type: String
    Description: "Nome globalmente único (ex.: aws-cloudformation-project-fiama-2025)"
  EnableVersioning:
    Type: String
    AllowedValues: ['Yes', 'No']
    Default: 'Yes'
  TagOwner:
    Type: String
    Default: Fiama

Conditions:
  UseVersioning: !Equals [!Ref EnableVersioning, 'Yes']

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration: !If
        - UseVersioning
        - Status: Enabled
        - !Ref 'AWS::NoValue'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      Tags:
        - Key: Owner
          Value: !Ref TagOwner

Outputs:
  BucketNameOut:
    Description: 'Nome do bucket criado'
    Value: !Ref S3Bucket
    Export:
      Name: dio-fiama:BucketName
  BucketArnOut:
    Description: 'ARN do bucket criado'
    Value: !GetAtt S3Bucket.Arn
